# Generated by Django 6.0 on 2026-01-13 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dat',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
