# Generated by Django 6.0 on 2026-01-13 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dat',
            new_name='date1',
        ),
        migrations.AddField(
            model_name='report',
            name='tim',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
