# Generated by Django 6.0 on 2026-01-13 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dat_report_date1_report_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tim',
        ),
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
