# Generated by Django 6.0 on 2026-01-13 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_report_tim_alter_report_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
