# Generated by Django 6.0 on 2026-01-13 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_report_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 16, 5, 42, 308195)),
        ),
    ]
