# Generated by Django 6.0 on 2026-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_report_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
