# Generated by Django 6.0 on 2026-01-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_report_date1'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount',
            field=models.IntegerField(default=12344),
        ),
        migrations.AddField(
            model_name='report',
            name='date2',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='platform',
            field=models.CharField(default='Whatsapp', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='select',
            field=models.CharField(default='Bug'),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('report', 'Report Page'), ('scam', 'Scam Page'), ('somethingelse', 'SomethingElse Page'), ('aboutus', 'About Us Page')], default='Unknown Page', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.TextField(default='Unknown'),
        ),
    ]
