# Generated by Django 6.0 on 2026-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_report_amount_report_date2_report_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
